[package]
name = "nio-console"
version = "0.1.0"
description = "A TUI console for Nio applications."
authors = ["Nur <nurmohammed840@gmail.com>"]
license = "Apache-2.0"
edition = "2024"

[dependencies]
crossterm = { version = "0.28", features = ["event-stream"] }
futures-core = "0.3"
ratatui = "0.30"
# nio = { path = "../nio-rt", version = "0.1" }
nio = { path = "../nio-rt", version = "0.1" }
