name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: nightly
          components: miri

    - name: Install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest

    - name: Run miri
      run: cargo +nightly miri nextest run --no-fail-fast

    - name: Run doc test
      run: cargo test --doc

    - name: Run tests
      run: cargo nextest run --no-fail-fast
